In [1]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

1.5.0
True


In [4]:
x = torch.randn(1)

if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    
    print(z)
    print(z.to("cpu", torch.double))

tensor([2.3246], device='cuda:0')
tensor([2.3246], dtype=torch.float64)


In [5]:
demo = torch.rand(5, 3)
print(demo)

tensor([[0.7199, 0.2692, 0.0226],
        [0.2191, 0.4700, 0.6953],
        [0.7051, 0.1146, 0.7328],
        [0.8003, 0.3762, 0.4656],
        [0.6325, 0.1266, 0.8025]])


In [7]:
zeros = torch.empty(2, 7)
print(zeros)

tensor([[-2.2329e+10,  4.5705e-41, -2.2329e+10,  4.5705e-41,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  6.2121e+22,  1.8788e+31,  1.7220e+22,
          2.4174e-06,  6.7948e-07]])


In [8]:
all_zero = torch.zeros(5, 3, dtype=torch.long)
print(all_zero)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
use_data = torch.tensor([5.5, 3])
print(use_data)

tensor([5.5000, 3.0000])


In [10]:
# 创建一个tensor 基于已经存在的tensor
# 其实就是size相似

x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x_star = torch.randn_like(x, dtype=torch.float)
print(x_star)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ 2.3578, -0.2921,  0.5968],
        [-0.8454,  1.3985, -0.5716],
        [-0.6127,  1.1427, -0.7086],
        [-1.5659, -0.2210, -1.7857],
        [ 0.5038, -1.0331, -1.4047]], device='cuda:0')


In [11]:
print(x_star.size())  // 这是一个元组

torch.Size([5, 3])


In [20]:
# 加法操作
y = torch.rand(5, 3)

# 注意 下面这两行虽然我现在不理解
# 但是很重要 因为没有的话 是没办法找到gpu的 还是默认在cpu上运算
# 错误信息： RuntimeError: expected device cpu but got device cuda:0
device = torch.device("cuda")
y = y.to(device)


print(y)
print("x + y =  ")

# 方法1： 直接使用数学运算符
# print(x + y)
# 方法2：使用自带的add方法
# print(torch.add(x, y))

# 还有更麻烦 但是看起来更正式的方法
# 就是首先定义一个输出结果tensor 然后将加法结果保存在里面
result = torch.empty(5, 3)
result = result.to(device)
torch.add(x, y, out=result)
print(result)

tensor([[0.1849, 0.0896, 0.1230],
        [0.1692, 0.9982, 0.2533],
        [0.9749, 0.0306, 0.6885],
        [0.7280, 0.2622, 0.6809],
        [0.7757, 0.8075, 0.6533]], device='cuda:0')
x + y =  
tensor([[1.1849, 1.0896, 1.1230],
        [1.1692, 1.9982, 1.2533],
        [1.9749, 1.0306, 1.6885],
        [1.7280, 1.2622, 1.6809],
        [1.7757, 1.8075, 1.6533]], device='cuda:0')


In [5]:
# 如果想要改变tensor的形状或者大小，使用torch.view

x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
# 明白了 看来还是很好用的 就直接根据需要转换了
k = z.view(-1, 4)

print(x.size(), y.size(), z.size())
print(x)
print("this is z, which is inferred from other dimensions")
print(z)
print(k)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[ 1.3995,  1.1496, -2.1956,  0.3068],
        [-0.3140,  1.9795,  0.5274, -0.5078],
        [-1.3488,  0.3151, -2.3698,  0.2878],
        [-0.5989,  1.4311, -1.1835,  0.2308]])
this is z, which is inferred from other dimensions
tensor([[ 1.3995,  1.1496, -2.1956,  0.3068, -0.3140,  1.9795,  0.5274, -0.5078],
        [-1.3488,  0.3151, -2.3698,  0.2878, -0.5989,  1.4311, -1.1835,  0.2308]])
tensor([[ 1.3995,  1.1496, -2.1956,  0.3068],
        [-0.3140,  1.9795,  0.5274, -0.5078],
        [-1.3488,  0.3151, -2.3698,  0.2878],
        [-0.5989,  1.4311, -1.1835,  0.2308]])


In [6]:
x = torch.randn(1)
print(x)

print(x.item())

tensor([-0.3989])
-0.39892321825027466
