autograd包会为Tensors上的所有操作提供自动微分。
它是一个由运行定义的框架，意味着代码以运行的方式来定义你的后向传播，而且每次的迭代都可以不同。


torch.Tensor 是包的核心类

属性.requires_grad设置为True，就会开始跟踪针对Tensor的所有操作。

完成计算之后，调用backward()来自动计算所有梯度。

该张量的梯度将累积到.grad属性中去。

要停止tensor历史记录的跟踪: .detach() 将其与计算历史记录分离

Tensor和Function互相连接并构建一个非循环图，将保存整个计算过程的历史信息。
每个张量都有一个grad_fn属性保存着创建了张量的Function的引用
如果是用户自己创建的，那么grad_fn = None

In [11]:
import torch

# 创建一个张量，设置requires_grad = True 来跟踪与其相关的计算
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [2]:
# 针对该张量做一个操作
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [3]:
print(y.grad_fn)

In [4]:
# more actions on y
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [5]:
# requires_grad_()会改变requires_grad标记。 输入的默认是False，如果没有提供相应的参数
a = torch.randn(2, 2)
a = (a * 3) / (a - 1)

print(a.requires_grad)

a.requires_grad_(True)
print(a.requires_grad)

b = (a * a).sum()
print(b.grad_fn)

False
True


In [6]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [7]:
# 雅可比向量积的例子
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
    
print(y)

tensor([1652.2782,  478.6860, -499.4943], grad_fn=<MulBackward0>)


In [8]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


In [9]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
